#!/usr/bin/env bash

rm -rf out/* || exit 0;

pip install -U mynt==0.2.3
mynt gen -f . out
( cd out
  git config user.name "Travis-CI"
  git config user.email "contact@travis-ci.com"
  cp ../CNAME ./CNAME
  git add .
  git commit -m "Deployed to Github Pages"
  git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages > /dev/null 2>&1
)
